#!/usr/bin/env bash

if [[ "${TRAVIS_TAG}" == "" ]]; then
    echo "No git tag present; exiting."
    exit 0
fi

docker build -t joeygibson/cucumber-tester .
docker tag joeygibson/cucumber-tester joeygibson/cucumber-tester:$TRAVIS_TAG
docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
docker push joeygibson/cucumber-tester:$TRAVIS_TAG


